<?php declare(strict_types = 1);

namespace Yormy\TranslationcaptainLaravel\Services\Generators;

use Illuminate\Filesystem\Filesystem;

class FilesGenerator
{

    protected array $labels;

    //protected string $exportPath = "temp" . DIRECTORY_SEPARATOR. "translation_export";
    protected string $exportPath;

    protected $header = "______GENERATED BY TRANSLATION CAPTAIN______";

    protected $settings;

    public function __construct(array $labels)
    {
        $this->labels = $labels;

//        ??
//        $this->app = App();
//        $this->files = new Filesystem();
    }

    public function setHeader(string $header) : self
    {
        $this->header = $header;
        return $this;
    }

    public function setExportPath(string $pathname) : self
    {
        $this->exportPath = $pathname;
        return $this;
    }



}
